FROM golang:latest
#WORKDIR /go/src/mypackage/myapp/
WORKDIR $GOPATH/src/mypackage/myapp/
COPY . .
RUN go get . && CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-w' -o web .
#ENTRYPOINT ["$GOPATH/src/mypackage/myapp/web"]
#Go programmed to listen on 5005 hence expose the port
EXPOSE 5005
CMD ["./web"]
